version = 1

test_patterns = ["/index.ts"]

exclude_patterns = ["/node_modules/**"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true