name: Node.js CI

on:
  push:
    branches:
    - main
    - development
  pull_request:
    branches:
    - main
    - development

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install typescript ts-node
    - run: ts-node index.ts
      env:
        BOT_MONGO_PATH: ${{ secrets.BOT_MONGO_PATH }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_SETTINGS_PATH: ${{ secrets.BOT_SETTINGS_PATH }}
        REPORTING_CHANNEL: ${{ secrets.REPORTING_CHANNEL }}
